name: Bump CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  bump-test:
    name: Bump Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.23, 1.22]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Download Bump dependencies
        run: go mod download

      - name: Verify Bump dependencies
        run: go mod verify

      - name: Run go vet on Bump
        run: go vet ./...

      - name: Run Bump unit tests
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload Bump coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: bump-unittests
          name: bump-codecov

  bump-lint:
    name: Bump Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go for Bump
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run golangci-lint on Bump
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

  bump-build:
    name: Bump Build & Test Binary
    runs-on: ubuntu-latest
    needs: [bump-test, bump-lint]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go for Bump build
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build Bump binary
        run: |
          make build

      - name: Test Bump binary functionality
        run: |
          ./bin/bump --version
          ./bin/bump --help

  bump-security:
    name: Bump Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go for Bump security scan
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run Gosec security scanner on Bump
        uses: securego/gosec@master
        with:
          args: './...'
