name: Bump Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  bump-release:
    name: Bump Binary Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go for Bump release
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run GoReleaser for Bump
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
